<a href="https://colab.research.google.com/github/titan-spyer/generative-ai/blob/main/CloudNotebooks/Pipeline_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch.nn as nn

In [27]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [28]:
df.shape

(569, 33)

In [29]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

## Train Test Split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [31]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [32]:
x_train

array([[-0.78026865,  0.24912729, -0.60811192, ...,  2.17229425,
         5.99982515,  4.80838532],
       [-0.63241839, -1.03991995, -0.62228988, ..., -1.03138573,
         0.36202619, -0.44372456],
       [-0.92253966, -1.6606604 , -0.95000322, ..., -1.27138691,
        -1.21187272, -0.95595402],
       ...,
       [ 0.21841803, -0.90911257,  0.19679093, ...,  0.34633102,
         0.08928122, -0.02615207],
       [-1.04249365, -1.03516332, -1.01684216, ..., -0.33764184,
         0.19517045,  0.66835968],
       [ 2.53101932,  1.74508801,  2.68603503, ...,  2.41351682,
         0.48075047,  0.19020673]])

In [33]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [34]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1])

In [46]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [47]:
x_train_tensor.shape

torch.Size([455, 30])

In [48]:
from torch.utils.data import  Dataset, DataLoader
class CustomDataset(Dataset):
  def __init__(self, features, lables):
    self.features = features
    self.lables = lables

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.lables[idx]

In [49]:
train_dataset = CustomDataset(x_train_tensor, y_train_tensor)
test_dataset = CustomDataset(x_test_tensor, y_test_tensor)

In [50]:
train_dataset[10]

(tensor([-0.3758, -0.7426, -0.4137, -0.4202, -0.1292, -0.8167, -0.6408, -0.8575,
          0.7314, -0.7018, -0.6174, -0.0103, -0.6505, -0.4851, -0.4812, -0.2385,
         -0.2155, -0.8867,  0.6357, -0.6144, -0.5072, -0.3591, -0.5512, -0.5084,
         -0.2636, -0.4801, -0.3591, -0.8766,  1.1321, -0.7293]),
 tensor(0.))

In [51]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

## Defining the Model

In [52]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

### Important Paramenters

In [53]:
learning_rate = 0.1
epochs = 25

In [54]:
loss_function = nn.BCELoss()

In [55]:
type(loss_function)

torch.nn.modules.loss.BCELoss

### Training Pipeline

In [56]:
# Create Model
model = MySimpleNN(x_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
# Define Loop
for epoch in range(epochs):
  for batch_features, batch_lables in train_loader:
    # Forward Pass
    y_pred = model(batch_features)
    # Loss Calculate
    loss = loss_function(y_pred, batch_lables.view(-1, 1))
    # Zero Gradients
    optimizer.zero_grad()
    # Backward class
    loss.backward()
    # Parameters Update
    optimizer.step()
    # Print Loss in each Epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.11838307231664658
Epoch: 2, Loss: 0.12959155440330505
Epoch: 3, Loss: 0.32195693254470825
Epoch: 4, Loss: 0.062046147882938385
Epoch: 5, Loss: 0.02644701488316059
Epoch: 6, Loss: 0.09125406295061111
Epoch: 7, Loss: 0.057574670761823654
Epoch: 8, Loss: 0.09614060074090958
Epoch: 9, Loss: 0.06113431230187416
Epoch: 10, Loss: 0.19196955859661102
Epoch: 11, Loss: 0.11164476722478867
Epoch: 12, Loss: 0.00631981436163187
Epoch: 13, Loss: 0.008590148761868477
Epoch: 14, Loss: 0.013125360943377018
Epoch: 15, Loss: 0.034026138484478
Epoch: 16, Loss: 0.01923183724284172
Epoch: 17, Loss: 0.1613347977399826
Epoch: 18, Loss: 0.00842530932277441
Epoch: 19, Loss: 0.007982423529028893
Epoch: 20, Loss: 0.07920026034116745
Epoch: 21, Loss: 0.010075665079057217
Epoch: 22, Loss: 0.04375087469816208
Epoch: 23, Loss: 0.02764212153851986
Epoch: 24, Loss: 0.010119381360709667
Epoch: 25, Loss: 0.09033199399709702

In [58]:
model.linear.weight

Parameter containing:
tensor([[ 0.4052,  0.4571,  0.7140,  0.4230,  0.1608,  0.0586,  0.2756,  0.7635,
          0.1568, -0.1331,  0.5978,  0.0256,  0.4714,  0.5468,  0.1766, -0.3646,
         -0.0801,  0.1286, -0.1713, -0.3710,  0.5519,  0.7318,  0.7417,  0.6989,
          0.4795,  0.1338,  0.5056,  0.7456,  0.4914,  0.0934]],
       requires_grad=True)

In [59]:
model.linear.bias

Parameter containing:
tensor([-0.3790], requires_grad=True)

### Evaluation

In [60]:
# Model Evaluation using test_loader
model.eval()
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_lables in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float()
    batch_accuracy = (y_pred.view(-1) == batch_lables).float().mean().item()
    accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accuracy: {overall_accuracy:.4f}")
# print(y_pred)

Accuracy: 0.9470