<a href="https://colab.research.google.com/github/titan-spyer/generative-ai/blob/main/CloudNotebooks/Pipeline_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch.nn as nn

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

## Train Test Split

In [5]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [7]:
x_train

array([[-0.514937  ,  1.79368724, -0.45360207, ...,  0.46828245,
         0.50762149,  2.02624698],
       [ 0.58431589,  0.04732171,  0.71387605, ...,  0.95010268,
         0.67651273,  0.41022956],
       [-0.70611142, -0.53242412, -0.75718713, ..., -1.10647684,
        -0.28600333, -0.87138206],
       ...,
       [ 0.81203836,  0.40134683,  0.79537539, ...,  1.02938955,
        -0.46309317, -0.44214477],
       [ 1.8972343 ,  1.37313391,  2.06676518, ...,  2.11958407,
         0.03866137,  0.81894776],
       [-0.32938536,  0.59617945, -0.19484165, ...,  1.38465574,
         2.41461668,  1.28866868]])

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
y_train

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [10]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
x_train_tensor.shape

torch.Size([455, 30])

## Defining the Model

In [22]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

### Important Paramenters

In [13]:
learning_rate = 0.1
epochs = 25

In [14]:
loss_function = nn.BCELoss()

In [15]:
type(loss_function)

torch.nn.modules.loss.BCELoss

### Training Pipeline

In [23]:
# Create Model
model = MySimpleNN(x_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
# Define Loop
for epoch in range(epochs):
  # Forward Pass
  y_pred = model(x_train_tensor.float())
  # Loss Calculate
  loss = loss_function(y_pred, y_train_tensor.float().unsqueeze(1))
  # Zero Gradients
  optimizer.zero_grad()
  # Backward class
  loss.backward()
  # Parameters Update
  optimizer.step()
  # Print Loss in each Epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8929423093795776
Epoch: 2, Loss: 0.6271557211875916
Epoch: 3, Loss: 0.4937840700149536
Epoch: 4, Loss: 0.41760361194610596
Epoch: 5, Loss: 0.36767148971557617
Epoch: 6, Loss: 0.3319826126098633
Epoch: 7, Loss: 0.3049697279930115
Epoch: 8, Loss: 0.2836735248565674
Epoch: 9, Loss: 0.26636403799057007
Epoch: 10, Loss: 0.2519572079181671
Epoch: 11, Loss: 0.23973697423934937
Epoch: 12, Loss: 0.2292100042104721
Epoch: 13, Loss: 0.2200246900320053
Epoch: 14, Loss: 0.2119230180978775
Epoch: 15, Loss: 0.20471110939979553
Epoch: 16, Loss: 0.19824020564556122
Epoch: 17, Loss: 0.19239403307437897
Epoch: 18, Loss: 0.18708036839962006
Epoch: 19, Loss: 0.18222489953041077
Epoch: 20, Loss: 0.17776703834533691
Epoch: 21, Loss: 0.17365685105323792
Epoch: 22, Loss: 0.16985277831554413
Epoch: 23, Loss: 0.16631977260112762
Epoch: 24, Loss: 0.16302824020385742
Epoch: 25, Loss: 0.1599528193473816

In [24]:
model.linear.weight

Parameter containing:
tensor([[ 0.2724,  0.2819,  0.1224,  0.2481,  0.1357,  0.0995,  0.2032,  0.2132,
          0.1544, -0.1471,  0.0358,  0.0861,  0.2160,  0.3719,  0.0404, -0.0652,
          0.0693, -0.0403, -0.0856, -0.0703,  0.4038,  0.2287,  0.2568,  0.2463,
          0.2348,  0.0919,  0.2871,  0.1474,  0.1439,  0.2508]],
       requires_grad=True)

In [25]:
model.linear.bias

Parameter containing:
tensor([-0.0661], requires_grad=True)

### Evaluation

In [26]:
# Model Evaluation
with torch.no_grad():
  y_pred = model(x_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor.float()).float().mean()
  print(f'Accuracy: {accuracy.item()}')
# print(y_pred)

Accuracy: 0.5320098400115967