<a href="https://colab.research.google.com/github/titan-spyer/generative-ai/blob/main/CloudNotebooks/Pipeline_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

## Train Test Split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train

array([[ 0.34351389,  2.64130856,  0.50253735, ...,  1.84361247,
         1.8113706 ,  3.13796266],
       [-1.00748444, -0.98136175, -0.97869917, ..., -0.31505584,
         0.14330934,  0.68165126],
       [ 0.31501182, -0.58759323,  0.31196891, ...,  0.1712126 ,
         0.75966499,  0.73360744],
       ...,
       [-0.93052884, -0.98367803, -0.94693777, ..., -1.2083658 ,
        -0.9801744 , -0.90853954],
       [-0.52009896, -1.37281397, -0.50062813, ..., -0.48517405,
         0.84392627,  0.45779749],
       [-0.71106286, -0.10812216, -0.73739498, ..., -0.76860341,
         0.58958204, -0.76096188]])

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0])

In [ ]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

## Defining the Model

In [ ]:
class MySimpleNN():
  def __init__(self, x) -> None:
    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.rand(1, dtype=torch.float64, requires_grad=True)


  def forward(self, x):
    z = torch.matmul(x, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


  def loss_function(self, y_pred, y):
    # Clamp Predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    # Calculate Loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

### Important Paramenters

In [ ]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [ ]:
# Create Model
model = MySimpleNN(x_train_tensor)
# Define Loop
for epoch in range(epochs):
  # Forward Pass
  y_pred = model.forward(x_train_tensor)
  # Loss Calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  # Backward class
  loss.backward()
  # Parameters Update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
  # Zero Gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  # Print Loss in each Epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.499084052792801
Epoch: 2, Loss: 3.365520359358093
Epoch: 3, Loss: 3.226297279790807
Epoch: 4, Loss: 3.0861955226992484
Epoch: 5, Loss: 2.9422713310233464
Epoch: 6, Loss: 2.794208362532793
Epoch: 7, Loss: 2.63964623509205
Epoch: 8, Loss: 2.4807737978921365
Epoch: 9, Loss: 2.3198307597482137
Epoch: 10, Loss: 2.16413688709693
Epoch: 11, Loss: 2.0139744460384503
Epoch: 12, Loss: 1.8680999232385218
Epoch: 13, Loss: 1.727170060702224
Epoch: 14, Loss: 1.5958393695668434
Epoch: 15, Loss: 1.4692517841613106
Epoch: 16, Loss: 1.3503091603148871
Epoch: 17, Loss: 1.2463088942607687
Epoch: 18, Loss: 1.1580064235277003
Epoch: 19, Loss: 1.0854282553495402
Epoch: 20, Loss: 1.027612077185487
Epoch: 21, Loss: 0.9826273450585182
Epoch: 22, Loss: 0.947964331946734
Epoch: 23, Loss: 0.9210764869902631
Epoch: 24, Loss: 0.8997816720460642
Epoch: 25, Loss: 0.8824095973941841

In [ ]:
model.weights

tensor([[-0.3962],
        [ 0.1330],
        [ 0.5522],
        [-0.0619],
        [ 0.4093],
        [-0.4154],
        [-0.1775],
        [-0.1505],
        [ 0.1848],
        [ 0.0314],
        [-0.3516],
        [ 0.0829],
        [ 0.4074],
        [ 0.3282],
        [ 0.3762],
        [-0.3286],
        [-0.1907],
        [ 0.2833],
        [ 0.6127],
        [-0.2016],
        [-0.4397],
        [ 0.0523],
        [ 0.2739],
        [ 0.1082],
        [ 0.4376],
        [ 0.1315],
        [-0.0267],
        [ 0.0223],
        [ 0.1518],
        [-0.1796]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([0.0474], dtype=torch.float64, requires_grad=True)

### Evaluation

In [ ]:
# Model Evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')
# print(y_pred)

Accuracy: 0.5161588191986084